name: myfm
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'


# -------------- PACKAGES -------------- #
dependencies:
  flutter:
    sdk: flutter
  
  # Utility Packages
  http: ^1.2.0
  intl: ^0.19.0
  logger: ^2.0.2+1
  lottie: ^3.1.0
  shimmer: ^3.0.0
  image_picker: ^1.0.8
  url_launcher: ^6.2.4
  connectivity_plus: ^5.0.1
  flutter_native_splash: ^2.3.10
  smooth_page_indicator: ^1.1.0

  # Icons
  iconsax: ^0.0.8 # https://iconsax-icon-list.netlify.app/
  cupertino_icons: ^1.0.2

  # State Magement
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.1
  google_sign_in: ^6.1.6
  firebase_storage: ^11.6.9
  cached_network_image: ^3.3.1

# -------------------------------------- #

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  # LOCAL ASSETS
  assets:
    - assets/icons/
    - assets/icons/continents/
    - assets/images/backgrounds/
    - assets/images/banners/
    - assets/images/default/
    - assets/images/on_boarding_images/
    - assets/logos/

  # LOCAL FONTS
  fonts:
    - family: IBM Plex Sans
      fonts:
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-Light.ttf
          weight: 300
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-Italic.ttf
          style: italic
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-Bold.ttf
          weight: 700
    - family: Libre Franklin
      fonts:
        - asset: assets/fonts/Libre_Franklin/LibreFranklin-Light.ttf
          weight: 300
        - asset: assets/fonts/Libre_Franklin/LibreFranklin-Regular.ttf
          weight: 400
        - asset: assets/fonts/Libre_Franklin/LibreFranklin-Italic.ttf
          style: italic
        - asset: assets/fonts/Libre_Franklin/LibreFranklin-Medium.ttf
          weight: 500
        - asset: assets/fonts/Libre_Franklin/LibreFranklin-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Libre_Franklin/LibreFranklin-Bold.ttf
          weight: 700
        - asset: assets/fonts/Libre_Franklin/LibreFranklin-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Libre_Franklin/LibreFranklin-Black.ttf
          weight: 900
